info: 'Check the flags of cpu'
task:
  - steps:
      - type: ssh
        ssh: "lscpu |grep Flags"
        result:
          set_value: cpu_flags
          verify: " [[ $cpu_flags == *avx2* ]] "
          err_msg: 'clock_source: #{clock_source}. recommended: tsc. Uneven CPU utilization during pressure testing resulted in low TPS during pressure testing'


